### ISSUE TITLE
com.fasterxml.jackson.core.JsonParseException: Unexpected character when using MariaDB

### ISSUE THREAD

**Issue by lorisbel** [vzakharchenko/keycloak-radius-plugin#494]
**Describe the bug**
I am trying to use MariaDB as RDBS, but I get the following error while starting the services:

`keycloak_1  | 11:58:42,655 FATAL [org.keycloak.services] (ServerService Thread Pool -- 66) Error during startup: java.lang.IllegalStateException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('"' (code 34)): was expecting comma to separate Object entries
keycloak_1  |  at [Source: (sun.nio.ch.ChannelInputStream); line: 1, column: 105]
keycloak_1  | 	at keycloak.plugins.radius//com.github.vzakharchenko.radius.configuration.FileRadiusConfiguration.getRadiusSettings(FileRadiusConfiguration.java:52)
keycloak_1  | 	at keycloak.plugins.radius//com.github.vzakharchenko.radius.radius.server.KeycloakRadiusServer.<init>(KeycloakRadiusServer.java:42)
keycloak_1  | 	at keycloak.plugins.radius//com.github.vzakharchenko.radius.radius.server.RadiusServerProviderFactory.createInstance(RadiusServerProviderFactory.java:20)
keycloak_1  | 	at keycloak.plugins.radius//com.github.vzakharchenko.radius.providers.AbstractRadiusServerProviderFactory.create(AbstractRadiusServerProviderFactory.java:19)
keycloak_1  | 	at keycloak.plugins.radius//com.github.vzakharchenko.radius.providers.AbstractRadiusServerProviderFactory.lambda$postInit$0(AbstractRadiusServerProviderFactory.java:41)
keycloak_1  | 	at org.keycloak.keycloak-server-spi-private@16.1.0//org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:239)
keycloak_1  | 	at keycloak.plugins.radius//com.github.vzakharchenko.radius.providers.AbstractRadiusServerProviderFactory.postInit(AbstractRadiusServerProviderFactory.java:40)
keycloak_1  | 	at org.keycloak.keycloak-services@16.1.0//org.keycloak.services.DefaultKeycloakSessionFactory.init(DefaultKeycloakSessionFactory.java:129)
keycloak_1  | 	at org.keycloak.keycloak-services@16.1.0//org.keycloak.services.resources.KeycloakApplication.createSessionFactory(KeycloakApplication.java:233)
keycloak_1  | 	at org.keycloak.keycloak-services@16.1.0//org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:124)
keycloak_1  | 	at org.keycloak.keycloak-wildfly-extensions@16.1.0//org.keycloak.provider.wildfly.WildflyPlatform.onStartup(WildflyPlatform.java:36)
keycloak_1  | 	at org.keycloak.keycloak-services@16.1.0//org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:114)
keycloak_1  | 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
keycloak_1  | 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
keycloak_1  | 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
keycloak_1  | 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.ConstructorInjectorImpl.constructOutsideRequest(ConstructorInjectorImpl.java:225)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:209)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.providerfactory.Utils.createProviderInstance(Utils.java:102)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.createProviderInstance(ResteasyProviderFactoryImpl.java:1385)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.ResteasyDeploymentImpl.createApplication(ResteasyDeploymentImpl.java:418)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.ResteasyDeploymentImpl.initializeObjects(ResteasyDeploymentImpl.java:265)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.ResteasyDeploymentImpl.startInternal(ResteasyDeploymentImpl.java:137)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.ResteasyDeploymentImpl.start(ResteasyDeploymentImpl.java:121)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:144)
keycloak_1  | 	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:42)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
keycloak_1  | 	at org.wildfly.security.elytron-web.undertow-server-servlet@1.10.1.Final//org.wildfly.elytron.web.undertow.server.servlet.RunAsLifecycleInterceptor.doIt(RunAsLifecycleInterceptor.java:70)
keycloak_1  | 	at org.wildfly.security.elytron-web.undertow-server-servlet@1.10.1.Final//org.wildfly.elytron.web.undertow.server.servlet.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:76)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:309)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:145)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:588)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:559)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
keycloak_1  | 	at org.wildfly.extension.undertow@26.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
keycloak_1  | 	at org.wildfly.extension.undertow@26.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
keycloak_1  | 	at org.wildfly.extension.undertow@26.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
keycloak_1  | 	at org.wildfly.extension.undertow@26.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
keycloak_1  | 	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:601)
keycloak_1  | 	at org.wildfly.extension.undertow@26.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:106)
keycloak_1  | 	at org.wildfly.extension.undertow@26.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:87)
keycloak_1  | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
keycloak_1  | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
keycloak_1  | 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
keycloak_1  | 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
keycloak_1  | 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
keycloak_1  | 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
keycloak_1  | 	at java.base/java.lang.Thread.run(Thread.java:829)
keycloak_1  | 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
keycloak_1  | Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('"' (code 34)): was expecting comma to separate Object entries
keycloak_1  |  at [Source: (sun.nio.ch.ChannelInputStream); line: 1, column: 105]
keycloak_1  | 	at com.fasterxml.jackson.core.jackson-core@2.12.3//com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2337)
keycloak_1  | 	at com.fasterxml.jackson.core.jackson-core@2.12.3//com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:710)
keycloak_1  | 	at com.fasterxml.jackson.core.jackson-core@2.12.3//com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:635)
keycloak_1  | 	at com.fasterxml.jackson.core.jackson-core@2.12.3//com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextFieldName(UTF8StreamJsonParser.java:1024)
keycloak_1  | 	at com.fasterxml.jackson.core.jackson-databind@2.12.3//com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:331)
keycloak_1  | 	at com.fasterxml.jackson.core.jackson-databind@2.12.3//com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
keycloak_1  | 	at com.fasterxml.jackson.core.jackson-databind@2.12.3//com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
keycloak_1  | 	at com.fasterxml.jackson.core.jackson-databind@2.12.3//com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
keycloak_1  | 	at com.fasterxml.jackson.core.jackson-databind@2.12.3//com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3585)
keycloak_1  | 	at org.keycloak.keycloak-core@16.1.0//org.keycloak.util.JsonSerialization.readValue(JsonSerialization.java:94)
keycloak_1  | 	at org.keycloak.keycloak-core@16.1.0//org.keycloak.util.JsonSerialization.readValue(JsonSerialization.java:79)
keycloak_1  | 	at keycloak.plugins.radius//com.github.vzakharchenko.radius.configuration.FileRadiusConfiguration.getRadiusSettings(FileRadiusConfiguration.java:49)
keycloak_1  | 	... 50 more
keycloak_1  | 
keycloak_1  | 11:58:42,664 INFO  [org.jboss.as.server] (Thread-1) WFLYSRV0220: Server shutdown has been requested via an OS signal
`

**To Reproduce**
1. User the folloging docker-compose.yml

`version: '3.7'
services:
  db:
    image: mariadb:10.5.3
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      
  keycloak:
    image: jboss/keycloak:latest
    depends_on:
      - db
    ports:
      - "8090:8080" #  UI
      - "8190:8190" #  DEBUG
      - "1812:1812/udp" #  RADIUS
      - "1813:1813/udp" #  RADIUS
    environment:
      - KEYCLOAK_IMPORT="/config/realm-example.json"
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=mariadb
      - DB_PORT=3306
      - DB_ADDR=db
      - DB_DATABASE=keycloak
      - DB_USER=root
      - DB_PASSWORD=root
      - RADIUS_SHARED_SECRET="secret"
      - RADIUS_UDP=true
      - RADIUS_UDP_AUTH_PORT=1812
      - RADIUS_UDP_ACCOUNT_PORT=1813
      - RADIUS_RADSEC=false
      - RADIUS_RADSEC_PRIVATEKEY="/config/private.key"
      - RADIUS_RADSEC_CERTIFICATE="/config/public.crt"
      - RADIUS_DICTIONARY=""
      - RADIUS_COA=false
      - RADIUS_COA_PORT="3799"
      - keycloak.profile.feature.upload_scripts="enabled"
    volumes:
      - ../cli:/opt/radius/cli
      - ./scripts:/opt/radius/scripts
      - ./config:/config
    entrypoint: /opt/radius/scripts/docker-entrypoint.sh`

2. Run using "docker-compose up"

**Comment by lorisbel** [comment]
My mistake... I solved by replacing  RADIUS_DICTIONARY="" with   RADIUS_DICTIONARY= in the docker compose file.
